### ISSUE TITLE
Adjust the naming pattern for plantings

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#10]
> A. Plantings
> 1. Name should be a concantenation of CFR, Compartment Number, Sub-Compartment Number and species code

We are already auto-generating Planting names, so this may just be a matter of changing the pattern of what we are concatenating together.

However, it also depends on whether or not we are collecting all the information we need for that. Need to see some examples of what this should look like.

**Comment by LeScruf** [comment]
So, each planting currently has a name field that is manually entered - this needs to go and be replaced with a script that concentanates the details entered in the planting form to CFR, Compartment Number, Sub-Compartment Number species code and season date - e.g. Mafuga/25/2/Eu-Gu/LR21 - that tells us everything we need to know (I think subject to confirmation) about the planting - location, species and age.

**Comment by mstenta** [comment]
Related to / blocked by #17
