### ISSUE TITLE
Season should be month of planting

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#11]
> A. Plantings
> 2. Season should be month of planting

Right now the Season field is not being populated on Plantings created by the Forest module. Should it be?

Month of planting might be a bit tricky because I assume it will be based on the "Planting date" in the Forest module form. What happens if someone changes that date? Do we need to auto-update the season? I assume so. So that requires extra logic.

**Comment by LeScruf** [comment]
I am confused - it seems the season IS being populated? https://nfa.farmos.net/farm/assets/plantings - I just added a season for the long-rains for 2021 - and it seems to work fine. If we enter a decade's worth of seasons (two a year most likely - long and short rains) then this will work.

**Comment by mstenta** [comment]
Ok - can we close this? I'm not sure "Seasons" will be useful for forest management in general. Perhaps we should just hide that field?
