### ISSUE TITLE
Range as a searchable group missing?

### ISSUE THREAD

**Issue by LeScruf** [Cambrico/farm_nfa#136]
'Range' is missing as an asset term on the dashboard and filters - so if one wants to search for all CFRs in a certain range, it appears one cant? This is quite important to be able to do.

**Comment by mstenta** [comment]
Ranges are represented as Land Assets in the system - with a "Range" option in the "Land type" field. They are not a dedicated Asset type. I forget the exact reasoning we had for this, but I see in our Google Docs notes document that it was mentioned on 2021-03-10

Can you describe a bit more how you envision such a search working @LeScruf ? Would it need to be a new block in the dashboard perhaps? What would it look like? What options would it provide? How would someone use it, ideally?

**Comment by LeScruf** [comment]
I think for now, unless there is a use scenario that is explicitly requested, we should depreciate this issue.
