### ISSUE TITLE
Change 'Location' to 'Sectors & CFRs'

### ISSUE THREAD

**Issue by LeScruf** [Cambrico/farm_nfa#142]
https://forests.nfa.go.ug/asset/799/locations - can the name of the 'Locations' tab be changed to 'Sectors & CFRs'? 

This would be clearer - I was hunting around for this for a while - and this relates somewhat to #136. 

Can this hierachy be made searchable in relation to #136 from the range downwards?

**Comment by pcambra** [comment]
I need to verify this has been deployed when the site is back

**Comment by pcambra** [comment]
@LeScruf this has been deployed and confirmed working on https://forests.nfa.go.ug/asset/799/locations
