### ISSUE TITLE
Ability to say that a particular area is occupied or available

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#25]
> Easy to find what areas are plantable, and which are not
> What stages crops are at

This could be a high-level report generator perhaps - that looks for any compartments without an active planting in them.

Related to #17

**Comment by mstenta** [comment]
Also:

> 4. Once a clear cut harvest has been logged, the compartment or sub-compartment can be released in the sytem for a new crop

**Comment by mstenta** [comment]
Also:

> 3. A compartment once planted - unless it has a sub-compartment that has not been planted should no longer be available for selection for planting, until it is harvested (i.e. released).

**Comment by mstenta** [comment]
As a first step, we could add some logic to the Area tab of plans (alongside #31).

**Comment by pcambra** [comment]
This will be done on #78
