### ISSUE TITLE
Split area selection into CFR + Compartment in Forest Plan Area tab

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#31]
Currently the Area tab of Forest Plans (/farm/plans/*/area) allows adding areas to the plan via a single auto-complete textfield.

We would like to split this into two dropdowns. The first should show a list of areas that are of type "CFR", and the second should be autopopulated based on the first selection, limited to areas of type "Compartment" that are children of that CFR (and sub-children).

If a CFR does not have any child Comparments, then don't show the second dropdown, and assign the CFR itself to the plan. If Compartments do exist, then assign the Compartments to the plan but not the CFR.

The CFR should only allow one selection, but the Compartments should allow multiple selections.

Notes from our call:

> Andrew wants the “Area” autocomplete to only show Compartments as options that are childs of a parent CFR
>     Two dependent fields
>     Need to figure out where to save the CFR vs Compartment reference
> Encourage creating areas OUTSIDE of the plan first

Relevant notes from requirements spreadsheet (although after discussion we will not be allowing creating areas from that tab - only selecting):

> 1. Areas should be restricted to relevant compartments and blocks (which are a subset of the CFR as per the area listing)
> "2. Redesign the 'Add area' field by dividing it into two:
i. Add exisiting area to plan as per the exisiting auto-search field
ii. Create new area and add it the plan via a button  (which prompts an overlay for adding/uploading new data as per the exisiting form on 'add area in 'areas' menu item)"

**Comment by mstenta** [comment]
See related: https://github.com/mstenta/farm_nfa/issues/25

**Comment by pcambra** [comment]
Remainder to be done on #121
