### ISSUE TITLE
Yield curve formula/plots

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#37]
From spreadsheet:

> 6. There should be a field for uploading projected yield curve  formula or plot.

> 2. The actual growth curve should be plottable against the projected growth curve (see 5D6) to visualize the overall performance of the crop and compartment.

> 4. The observations also need to be cross analysable so that queries can be run of overall volumes by species and year of planting across CFR, Range and Forest Estate etc. with graphical depictions

From call notes:

> 2. Link inventory data into the plot of yield curve

> 4. Perhaps a new custom View that lives in a report outside of specific plans, which can summarize the same inventory information that is in plans

**Comment by pcambra** [comment]
Related to #73

**Comment by LeScruf** [comment]
Yes merge with #73
