### ISSUE TITLE
Improve area hierarchy process

### ISSUE THREAD

**Issue by mstenta** [Cambrico/farm_nfa#7]
> The user interface of the 'relations' field needs to be improved and made much easier to use (given the long list of areas).

It sounds like the main problem here is that editing the area hierarchy is difficult with so many areas. Normally I would suggest using the click-and-drag UI at /admin/structure/taxonomy/farm_areas, but even that is a bit difficult to use. I assume Andrew found the "Relations" fields to be an easier way to do it... but still has issues because the list is so long.

**Comment by LeScruf** [comment]
We need to fix this somehow - as it's going to get very confused very quickly when we start working at compartment level - there will be 500 x 'Compartment 1's etc. - for each forest reserve - and unless the hierarchy process and workflow is very straight-forward on the UI, it's gonna be fun (not). But if this is cracked it'll make the system impressively powerful.

**Comment by mstenta** [comment]
If the "Relations" fields was an autocomplete text search for choosing the parent, would this work?

In general, the idea of having 500 areas under EACH forest reserve may prove to be a big problem in itself (apart from managing hierarchy). Taxonomy terms are really not designed for this kind of volume. In farmOS 2.x we plan to move areas to assets, but even there - this is a lot. So it makes me really wonder if we actually need separate records for each, or if we can take a different approach entirely for some of these geometries.

I think it boils down to the question: will you need to associate logs and assets with those very granular areas?

I assume the answer to that is "yes".

An alternative might be: we could consider building a custom entity type for Compartments specifically.

This will need a lot more thought and discussion between the three of us - we may find that we run up against some serious limitations using the Areas as they work now.

Leaving the "needs clarification" label so that we remember to follow-up together.

**Comment by mstenta** [comment]
I opened a separate issue just for figuring out the compartment question: https://github.com/mstenta/farm_nfa/issues/17

We can leave this one for the hierarchy discussion.
