### ISSUE TITLE
New planting log type for plans

### ISSUE THREAD

**Issue by pcambra** [Cambrico/farm_nfa#92]
See notes from https://docs.google.com/document/d/1DtT3WLLfm9gCbkRVGKGhthVztVfl3P96zFZ4A7X6Wp8/edit#

Planting/Enrichment tab
- Keep it separate from Management, so that additional logic/UI can be added (eg: making sure you don’t plant the same compartment)
- A map of all compartments in the plan, with some indication of which ones are planted, and which ones aren’t

Add Planting tab for both natural and plantation plans:

- "Planting" tab on plantation plans. "Enrichment" tab for natural plans.
- Between Summary and Management
- Form:
  - Tree species (saved to Forest asset). Single value field. If multiple tree species are wanted on a compartment for natural forests, multiple logs and multiple forest assets (one per each species) need to be added.
  - Location
  - Date
  - Total trees planted (manually entered). Quantity entity: Count/trees
  - Number of hectares (manually entered): Quantity entity: Area/ha
  - Tree spacing (manually entered): Quantity entity: Length/metres
  - Number of seedlings per hectare (automatically calculated): total trees/ha ?
  - Source / origin (saved to Forest asset). 
  
- Validation
  - Only for plantations: A compartment can only have one forest asset. (Asset location service to see if there are assets in a location).  

Add Source / Origin field to Forest assets. Taxonomy tag with auto-create.
Add Tree species field to Forest assets (will be done on #126) 

**On submit, it will create a planting log but it should also create an asset forest.** When doing it from a plantation plan, it will auto-fill forest type to plantation forest, natural stand from natural plans.

On Log Add:

  - Tree species 
  - Location
  - Date
  - Total trees planted 
  - Number of hectares 
  - Tree spacing 
  - Source / origin

On Log Edit:

  - Tree species (disabled)
  - Location
  - Date
  - Total trees planted 
  - Number of hectares 
  - Tree spacing 
  - Number of seedlings per hectare (calculated)
  - Source / origin (disabled)

On Log delete:

- Delete the log and the forest (watch out integrity first, the forest needs to be deleted first, as there might be another log attached to it). This means that the DELETE action has validation and show an error (related to #109)

**Comment by pcambra** [comment]
@mstenta can we haz the tree species from the old system? i.e migration? export?

**Comment by pcambra** [comment]
![image](https://user-images.githubusercontent.com/104912/138103954-d3006d4a-7bb0-4f55-a660-dfe6aedd4702.png)

**Comment by pcambra** [comment]
@LeScruf all is ready to review except from the "Number of seedlings per hectare (automatically calculated): total trees/ha ?" field, working on that

**Comment by pcambra** [comment]
Pushed a couple of changes, one for the seedling and another for the enrichment label.

I think this is missing, but not sure what it means now:

`
    Only for plantations: A compartment can only have one forest asset. (Asset location service to see if there are assets in a location).
`

After a conversation with @mstenta, I think the approach I've taken is wrong and we need to partially redo this ticket but also some assumptions I've been having from the beginning (i.e. how to display locations contextual to the plan in the log form).

I think we need a deeper conversation about this as I'm really lost at this point.

**Comment by mstenta** [comment]
No worries @pcambra ! We can discuss on our next call. This is a particularly complex piece, at least conceptually. I think the implementation should be relatively simple once it is well understood. I'll do my best to clarify the thoughts when we talk.

In the meantime, here are some key points, which may help (but talking together will be best no matter what):

- The planting form should create both a `forest` asset and a `planting` log. This works almost exactly the same as the "Planting" quick form in farmOS 1.x, which creates an asset to represent the crop being planted, and log(s) to represent the events that "move" this asset to a place.
- In order for the `planting` log to be a "movement" (in farmOS terminology), it must reference the `forest` asset in the log's `asset` field, the `compartment` asset(s) that the forest will be located in must be referenced in the log's `location` field, and the log's `is_movement` boolean field must be set to `TRUE`. This will signify that the `forest` was "moved" to the `compartment` locations at the time of the log's timestamp.
- One of the key things to understand, which is confusing, is that `forest` assets will be considered "moveable assets" in this system. See the farmOS data model docs to understand what a "moveable asset" is: https://docs.farmos.org/model/logic/location/#movable-assets - One might ask: How can a "forest" be "moveable"?? In this system `forest` assets represent that collection of trees that are being intentionally managed. In many cases, these trees are raised in a nursery, and then transplanted to a compartment. This is a movement. But the trees are the same. This is notably different from using "location hierarchy" of assets to designate a forest is "inside" a compartment, which does not track those individual movements over time. This is the important distinction with `forest` assets in this system.
- After the `forest` asset is created, and the `planting` log "moves" it to a `compartment` asset, then it is possible to look up all the `forest` assets in that `compartment` using the "asset location" service. This will be necessary for referencing the `forest` asset in the other logs (created via Management, Inventory, and Harvest tabs). I described this in my other comment here: https://github.com/mstenta/farm_nfa/issues/132#issuecomment-956141393

With these two pieces together, users will be able to create `forest` assets (and "move" them to a compartment in the same step), and then over the course of their lifecycle users can record management/inventory/harvest logs that reference the `forest` assets (as well as the `compartment` assets, for extra context). The end result of this is that forest managers will be able to view *either* the `forest` assets directly, or the `compartment` assets to get a full history of what has happened in relation to them. And it sets us up to be able to add nursery features in the future as well.

Hope that helps to provide a bit more context/reasoning! Let's talk it all through on the next call either way. :-)

**Comment by mstenta** [comment]
> not sure what it means now:
> 
> > Only for plantations: A compartment can only have one forest asset. (Asset location service to see if there are assets in a location).

With the above explanation in mind, I can also explain how this piece can work.

Since the `forest` asset is "located in" the `compartment` asset (because it was "moved" there via the `planting` log), we can can use that to check whether or not a compartment has any `forest` assets in it or not. See the example in this comment: https://github.com/mstenta/farm_nfa/issues/132#issuecomment-956141393

The idea is: in a Plantation plan, users should not be able to create multiple `forest` assets within a single `compartment`. This is a business logic rule for NFA, and only applies to Plantation plans... not Natural Forest plans (where unlimited `forest` assets can be created in a `compartment`). We can enforce this with some validation in the planting form that checks to see if the `compartment` has any `forest` assets in it already (using `\Drupal::service('asset.location')->getAssetsByLocation($locations)` code). If it does, then prevent creating a new forest via the planting form with a validation message along the lines of: "Only one tree species can be planted in a compartment at a time. Please choose a different tree species, or choose a different compartment."

**Comment by pcambra** [comment]
@mstenta I've been playing with this a bit and a major question has brought is, how do we relate the logs with the plans then? we were using the asset field to make the bridge but there's nothing now as far as I can see.

**Comment by mstenta** [comment]
Ah good question - do you mean specifically for building the Views of Logs that are displayed on the Management, Harvest, Inventory, etc tabs within Plans? Were those relying on the `asset` field for the relationship previously? And if so, how? Were they referencing the same CFRs that the Plan itself was referencing?

One way to do this might be to use the `log` reference field that exists on the Plans. So the Plans would reference the Logs - in addition to referencing CFRs. This would simplify the Views relationship. But it would mean you need to update the Plan every time one of those logs are saved too.

That might make the most sense from a purely "data model" standpoint.

**Comment by pcambra** [comment]
@mstenta I think I must be missing something else, I'm forcing the planting logs to be movement ones (they have is_movement to TRUE), then the logs are assigned a forest in the asset field. However, I don't see the location or parents added to the forest asset and `\Drupal::service('asset.location')->getAssetsByLocation($locations)` is empty, so I'm guessing I'm doing something wrong, but can't figure out what

**Comment by pcambra** [comment]
"Only one stand can be planted in a compartment at a time. Please choose a different compartment."

**Comment by pcambra** [comment]
@LeScruf Just a quick update, @mstenta and I just figured out what the issue was and I'll be pushing this as soon as I can (hopefully early next week)

**Comment by pcambra** [comment]
@LeScruf I think this is now ready for testing :)

**Comment by pcambra** [comment]
On meeting 21/04/2022, @LeScruf to provide further feedback
